services:
  app:
    build: .
    ports:
      - '3106:3000'
    volumes:
      - /data/punttikuuri:/app/data
    restart: unless-stopped
    environment:
      - PUBLIC_LOGO_LINK_URL=${LOGO_LINK_URL}
